### ISSUE TITLE
Generated whitespace is off

### ISSUE THREAD

**Issue by benhaynes** [directus/extension-static-generator#1]
```
<body>
    <ul>
    {% for task in directus.tasks %}
        <li>
            Task: {{ task.task }}
        </li>
    {% endfor %}
    </ul>
</body>
```

Generates
```
<body>
    <ul>
            <li>
            Task: Test 2
        </li>
        </ul>
</body>
```

Should generate
```
<body>
    <ul>
        <li>
            Task: Test 2
        </li>
    </ul>
</body>
```

**Comment by jasekz** [comment]
I looked into this issue and tried several things, including encoding without the 'bom' markers, but nothing fixed the issue.  I suspect it's something to do with the Twig syntax causing this issue, in this case '{%', because the other code appears to align as expected.
