### ISSUE TITLE
New page path

### ISSUE THREAD

**Issue by benhaynes** [directus/extension-static-generator#22]
Right now you need to use `/page.html` to get into the project root. You shouldn't need the `/`, it should default to the project root. 

Also, there should be no way to generate outside of the project root used in the config.

**Comment by jasekz** [comment]
This works as expected for me.  The slash gets removed during normalization, so this shouldn't differ between the two.
http://www.awesomescreenshot.com/image/2872531/63808018ce199371c8d7d92a03e98f9b
