### ISSUE TITLE
Parsing footer include

### ISSUE THREAD

**Issue by benhaynes** [directus/extension-static-generator#24]
I have a footer being included with the following code: `© Directus 2017`

But it's generating as `Â© Directus 2017`

For reference, this is the import code: `{% include 'includes/footer.html' %}`

Maybe the generator isn't setup for UTF8?

**Comment by jasekz** [comment]
This isn't really a saving or twig issue, but rather an html/browser issue.  The same problem occurs if I copy `©` directly into a raw html file, however, using &copy; solves the issue.
